name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y autoconf automake libtool libtool-bin libltdl-dev pkg-config zlib1g-dev cmake libffi-dev libssl-dev libsqlite3-dev
          pip install "Cython==0.29.36" buildozer git+https://github.com/kivy/python-for-android.git
          

      - name: Build APK with Buildozer
        run: |
          buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HADS-Tracker-APK
          path: bin/*.apk
